name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # main branch'e push olunca tetiklensin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t queryrunner-api:latest .
          docker tag queryrunner-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/queryrunner-api:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/queryrunner-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/queryrunner-api:latest
            docker stop queryrunner || true
            docker rm queryrunner || true
            docker run -d -p 8000:8000 --name queryrunner ${{ secrets.DOCKER_HUB_USERNAME }}/queryrunner-api:latest
